main:
    params: [event]
    steps:
        - log_event:
            call: sys.log
            args:
                text: ${event}
                severity: INFO
        - decode_pubsub_message:
            assign:
            - base64: ${base64.decode(event.data.data)}
            - message: ${text.decode(base64)}
        - return_pubsub_message:
                return: ${message}
