steps:
- # Build event_handler image
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=gcr.io/$PROJECT_ID/notifier:${_TAG}', '.']
  id: build

- # Push the container image to Container Registry
  name: gcr.io/cloud-builders/docker
  args: ['push', 'gcr.io/$PROJECT_ID/notifier:${_TAG}']
  waitFor: [build]
  id: push

images: [
  'gcr.io/$PROJECT_ID/notifier:${_TAG}'
]
substitutions:
  _TAG: v1